# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv', '~> 2.7', require: false
gem 'geocoder', '~> 1.6'
gem 'sinatra', '~> 2.2'
gem 'sinatra-contrib', '~> 2.0'
gem 'sinatra-param', '~> 1.6', require: 'sinatra/param'
gem 'weatherb', '~> 0.1'
